Lisa login page
DevPreps/frontend pull request #21
Opened 2022-08-18 10:13 UTC by 2016lisali

1. add "error", "info", "success", "warning" color variables in theme palette. 
2. add login and register page
3. refactor if else statement in contact.tsx file and refactor the test file
4. remove alert from contact.tsx file. The undeliverable email address error will be displayed in the message box under the contact form. 
5. change button and link colours according to the theme colour variables

2022-08-18 23:36 UTC, QiujuYang approved these changes
Looks very nice.

2022-08-20 23:48 UTC, Jet004 requested changes
Nice work overall, just a few things which may become problems in the future which we should be aware of

2022-08-20 23:48 UTC, Jet004 commented on src/pages/myAccount/MyProfile.tsx
> +            sm: "calc(100vh - 64px - 305px)", // 100vh - header height - footer height
As above, hard coded values can cause problems if something changes. We should find a better, more dynamic, solution.

2022-08-20 23:48 UTC, Jet004 commented on src/pages/myAccount/MyProfile.tsx
> +        minHeight: "630px",
As above

2022-08-21 23:18 UTC, 2016lisali commented on src/pages/Login.tsx
> +        height: "calc(100vh - 64px - 305px)", // 100vh - header height - footer height
Changed to flexGrow. Thank you for your suggestion :)

2022-08-21 23:20 UTC, 2016lisali commented on src/pages/Login.tsx
> +        minHeight: "526px",
The mine-height was nolonger needed after using flexGrow. Thank you for the suggestion :).

2022-08-21 23:21 UTC, 2016lisali commented on src/pages/Login.tsx
> +        color: "grey",
The colour was replaced by theme colors. Thank you for the suggestion :)

2022-08-21 23:26 UTC, 2016lisali commented on src/pages/Register.tsx
> +        minHeight: "691px",
minHeight has been deleted. When using the calc height, the footer will cover the form in short height screen size, so minHeight was setting to fix this issue. minHeight is no longer needed when using flex-grow.

2022-08-21 23:29 UTC, B08waffles approved these changes
Look's good, I agree with Jet's feedback here, good to see your using the ? where you can, makes for a much more stable system that way, good work!.

2022-08-22 03:43 UTC, 2016lisali commented on src/data.tsx
> -        description:
Add buildArray in data.ts file, and add randomiser to set random category, tags and position. Add interviewItems for interview posts.

2022-08-22 04:33 UTC, Jet004 approved these changes
Great work! looking really good!

2022-08-22 05:01 UTC, merged