Chris wysiwyg
DevPreps/frontend pull request #24
Opened 2022-08-25 07:19 UTC by galarist

Adding a WYSIWYG editor for our project.

2022-08-25 09:32 UTC, B08waffles approved these changes

2022-08-25 10:58 UTC, 2016lisali requested changes

2022-08-25 10:58 UTC, 2016lisali commented on src/forms/RichTextEditor.tsx
> +            onChange={setValue}
We are using React-hook-form to handle the form state. This is the post content data, should we implement react-hook-form here or pass the data to onSubmit funtions in ComposePost and UpdatePost components?

2022-08-25 10:58 UTC, 2016lisali commented on src/forms/__tests__/RichTextEditor.test.tsx
> +        console.log(wrapper.debug());
This console.log should be deleted, otherwise it will be logged out with every test

2022-08-25 12:41 UTC, 2016lisali approved these changes

2022-08-26 02:20 UTC, QiujuYang approved these changes

2022-08-26 04:05 UTC, galarist commented
Co-authored-by: Lisa Li @2016lisali

2022-08-26 04:06 UTC, merged