style: different style to active button on current page
DevPreps/frontend pull request #30
Opened 2022-09-02 02:53 UTC by galarist

Co-Authored-By: Lisa Li <61769853+2016lisali@users.noreply.github.com>

2022-09-02 12:53 UTC, 2016lisali requested changes
Look good. Just 1 tiny part needs to be modified :)

2022-09-02 12:53 UTC, 2016lisali commented on src/components/TopNav.tsx
> +        marginLeft: 0.5,
marginLeft and marginRight can be replaced with mx: 0.5 which is much simpler :)

2022-09-02 13:09 UTC, 2016lisali approved these changes
Good work, thanks, Chris.

2022-09-02 14:01 UTC, QiujuYang approved these changes

2022-09-03 12:05 UTC, B08waffles approved these changes
Looks good, I like how you've used the `...` operator to use two styles at once, well done!

2022-09-03 12:13 UTC, merged