Feat routes
DevPreps/frontend pull request #6
Opened 2022-07-25 23:42 UTC by 2016lisali

Too many changes for this pull request. I should commit, push and create pull requests more frequently:)

2022-07-26 04:02 UTC, Jet004 requested changes

2022-07-26 10:18 UTC, Claire-bk approved these changes

2022-07-27 01:10 UTC, Jet004 requested changes

2022-07-27 01:10 UTC, Jet004 commented on package.json
> +        "start": "parcel public/index.html && parcel watch public/index.html",
This is a bit like duplicating the command. You should just be able to run 'parcel watch public/index.html'

2022-07-27 02:52 UTC, QiujuYang approved these changes

2022-07-28 03:09 UTC, Jet004 approved these changes

2022-07-28 03:09 UTC, merged